# Base configs
baseurl: "https://savelle-anthony.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Savelle Anthony"
subtitle: ""
author: "Savelle Anthony"
header:
 title: "Photography"
 subtitle: "by Savelle Anthony"
footer:
 name: "About Savelle"
 bio: "I'm a new photographer, hoping to learn as much as possible"
social_urls:
  github: "https://www.github.com/savelle-anthony"
